

services:
  bot:
    container_name: bot
    build:
      context: ./bot
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "50053:50053"
    depends_on:
      - postgres
      - predict_age1
    networks:
      - backend

  predict_age1:
    container_name: predict_age1
    build:
      context: ./predict_age
      dockerfile: ./Dockerfile
    environment:
      - GRPC_HOST_LOCAL=0.0.0.0
      - GRPC_PORT=50051
    ports:
      - "50051:50051"
    networks:
      - backend

  detect_disease1:
    container_name: detect_disease1
    build:
      context: ./detect_disease
      dockerfile: ./Dockerfile
    environment:
      - GRPC_HOST_LOCAL=0.0.0.0
      - GRPC_PORT=50052
    ports:
      - "50052:50052"
    networks:
      - backend

  postgres:
    container_name: postgresql
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - backend
volumes:
  postgres_data:

networks:
  backend:

