# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: microservices/predict/proto/predict_disease.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'microservices/predict/proto/predict_disease.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1microservices/predict/proto/predict_disease.proto\x12\x07predict\"\"\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"2\n\x11\x44\x65tectionResponse\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x0e\n\x06report\x18\x02 \x01(\t2T\n\x0ePredictDisease\x12\x42\n\rDetectDisease\x12\x15.predict.ImageRequest\x1a\x1a.predict.DetectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'microservices.predict.proto.predict_disease_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=62
  _globals['_IMAGEREQUEST']._serialized_end=96
  _globals['_DETECTIONRESPONSE']._serialized_start=98
  _globals['_DETECTIONRESPONSE']._serialized_end=148
  _globals['_PREDICTDISEASE']._serialized_start=150
  _globals['_PREDICTDISEASE']._serialized_end=234
# @@protoc_insertion_point(module_scope)
