# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: predict_age.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'predict_age.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11predict_age.proto\x12\x0bpredict_age\"\"\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"3\n\x12PredictionResponse\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x0e\n\x06report\x18\x02 \x01(\t2V\n\nPredictAge\x12H\n\nPredictAge\x12\x19.predict_age.ImageRequest\x1a\x1f.predict_age.PredictionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'predict_age_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=34
  _globals['_IMAGEREQUEST']._serialized_end=68
  _globals['_PREDICTIONRESPONSE']._serialized_start=70
  _globals['_PREDICTIONRESPONSE']._serialized_end=121
  _globals['_PREDICTAGE']._serialized_start=123
  _globals['_PREDICTAGE']._serialized_end=209
# @@protoc_insertion_point(module_scope)
