# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import predict_disease_pb2 as predict__disease__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in predict_disease_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PredictDiseaseStub(object):
    """Сервис для детекции объектов с помощью модели YOLO
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectDisease = channel.unary_unary(
                '/predict_disease.PredictDisease/DetectDisease',
                request_serializer=predict__disease__pb2.ImageRequest.SerializeToString,
                response_deserializer=predict__disease__pb2.DetectionResponse.FromString,
                _registered_method=True)


class PredictDiseaseServicer(object):
    """Сервис для детекции объектов с помощью модели YOLO
    """

    def DetectDisease(self, request, context):
        """Метод Detect принимает изображение и возвращает список обнаруженных объектов
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PredictDiseaseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectDisease': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectDisease,
                    request_deserializer=predict__disease__pb2.ImageRequest.FromString,
                    response_serializer=predict__disease__pb2.DetectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'predict_disease.PredictDisease', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('predict_disease.PredictDisease', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PredictDisease(object):
    """Сервис для детекции объектов с помощью модели YOLO
    """

    @staticmethod
    def DetectDisease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/predict_disease.PredictDisease/DetectDisease',
            predict__disease__pb2.ImageRequest.SerializeToString,
            predict__disease__pb2.DetectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
