# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: predict_disease.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'predict_disease.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15predict_disease.proto\x12\x0fpredict_disease\"\"\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"C\n\x11\x44\x65tectionResponse\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x0e\n\x06report\x18\x02 \x01(\t\x12\x0f\n\x07\x64isease\x18\x03 \x01(\t2d\n\x0ePredictDisease\x12R\n\rDetectDisease\x12\x1d.predict_disease.ImageRequest\x1a\".predict_disease.DetectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'predict_disease_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=42
  _globals['_IMAGEREQUEST']._serialized_end=76
  _globals['_DETECTIONRESPONSE']._serialized_start=78
  _globals['_DETECTIONRESPONSE']._serialized_end=145
  _globals['_PREDICTDISEASE']._serialized_start=147
  _globals['_PREDICTDISEASE']._serialized_end=247
# @@protoc_insertion_point(module_scope)
